services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3005:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro  
  node-app:
    build: . 
    image: sandun1/node-app 
   
    environment:
      - PORT=3005
    depends_on:
      - mongo  

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: sandun
      MONGO_INITDB_ROOT_PASSWORD: 123
    volumes:
      - mongo-db:/data/db 

  redis:
    image: redis   
    ports:
      - "6379:6379"
     

volumes:
  mongo-db:    


  
