services:
  nginx:
    ports:
      - "3005:80"
  node-app:
    build:
      context: .
      args: 
       NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=sandun
      - MONGO_PASSWORD=123
      - SESSION_SECRET=secret

    command: npm run start  

  mongo:
    environment:
     - MONGO_INITDB_ROOT_USERNAME=sandun
     - MONGO_INITDB_ROOT_PASSWORD=123 


      
      